server:

  # 服务器端口号为 8300
  port: 8300

wenepu:

  #  和鉴权业务逻辑有关的配置项
  authentication:
    web-verification-url: http://jwgl.nepu.edu.cn/verifycode.servlet
    header-j-session-id-key: Set-Cookie
    login-url: http://jwgl.nepu.edu.cn/Logon.do
    method-key: method
    method-value: logon
    student-number-key: USERNAME
    student-password-key: PASSWORD
    verification-code-key: RANDOMCODE
    cookie-key: JSESSIONID
    timeout: 5000
    error-title-length: 21
    first-redirect-url: http://jwgl.nepu.edu.cn/framework/main.jsp
    second-redirect-url: http://jwgl.nepu.edu.cn/Logon.do
    second-redirect-method-value: logonBySSO
    get-app-token-method-value: authUser
    get-app-token-student-number-key: xh
    get-app-token-student-password-key: pwd
    get-app-token-url: http://jwgl.nepu.edu.cn/app.do
    app-token-json-key: token
    error-app-token: -1


  # 和开课学期相关业务逻辑有关的配置项
  semester:
    list-all-url: http://jwgl.nepu.edu.cn/tkglAction.do
    method-key: method
    method-value: kbxxXs
    cookie-key: JSESSIONID
    timeout: 10000
    error-title: 出错页面
    select-element-id: xnxqh
    option-element-name: option
    spring-semester-original-end-with: 1
    spring-semester-alias: 春季学期
    autumn-semester-alias: 夏季学期
    semester-alias-separator: ' 年'

  # 和成绩业务逻辑有关的配置项
  score:
    method-key: method
    cookie-key: JSESSIONID
    timeout: 5000
    error-title: 出错页面
    td-element-name: td
    span-element-name: span
    tr-element-name: tr
    a-element-name: a
    attribute-onclick-key: onclick
    get-by-semester-original-url: http://jwgl.nepu.edu.cn/xszqcjglAction.do
    get-by-semester-original-method-value: queryxscj
    get-by-semester-original-semester-original-key: kksj
    total-credit-td-father-element-id: tblBm
    score-item-tr-father-element-id: mxh
    get-detail-by-detail-uri-base-url: http://jwgl.nepu.edu.cn/xszqcjglAction.do?method=querypscj&
