server:

  # 服务器端口号为 8300
  port: 8300

wenepu:

  #  和鉴权业务逻辑有关的配置项
  authentication:
    web-verification-url: http://jwgl.nepu.edu.cn/verifycode.servlet
    header-j-session-id-key: Set-Cookie
    login-url: http://jwgl.nepu.edu.cn/Logon.do
    method-key: method
    method-value: logon
    student-number-key: USERNAME
    student-password-key: PASSWORD
    verification-code-key: RANDOMCODE
    cookie-key: JSESSIONID
    timeout: 5000
    error-title-length: 21
    first-redirect-url: http://jwgl.nepu.edu.cn/framework/main.jsp
    second-redirect-url: http://jwgl.nepu.edu.cn/Logon.do
    second-redirect-method-value: logonBySSO


  # 和开课学期相关业务逻辑有关的配置项
  semester:
    list-all-url: http://jwgl.nepu.edu.cn/tkglAction.do
    method-key: method
    method-value: kbxxXs
    cookie-key: JSESSIONID
    timeout: 10000
    error-title: 出错页面
    select-element-id: xnxqh
    option-element-name: option
    spring-semester-original-end-with: 1
    spring-semester-alias: 春季学期
    autumn-semester-alias: 夏季学期
    semester-alias-separator: ' 年'
